language: python

git:
  autocrlf: input

install: pip install -U tox
script: tox -v

_anchors:
  - &refreshpath eval $(powershell -NonInteractive -Command 'write("export PATH=`"" + ([Environment]::GetEnvironmentVariable("PATH","Machine") + ";" + [Environment]::GetEnvironmentVariable("PATH","User")).replace("\","/").replace("C:","/c").replace(";",":") + ":`$PATH`"")')

jobs:
  include:
    - stage: test
      os: windows
      language: shell
      before_install:
        - choco install python3
        - *refreshpath
        - python --version
        - pip --version
      env: TOXENV=py3
    - os: osx
      language: shell
      env: TOXENV=py3
    - python: 3.5
      env: TOXENV=py
    - python: 3.6
      env: TOXENV=py
    - python: 3.7
      env: TOXENV=py
    - python: 3.8
      env: TOXENV=py
    - python: 3.5
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=docs

    - stage: coverage
      python: 3.5
      env: TOXENV=cov
      before_script: pip install -U coveralls
      after_success: coveralls

    - stage: deploy
      python: 3.5
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: renatahodovan
        password:
          secure: Mtflkx67kYyBxsrEe188psBg4Gz38Zgd2YvBjHB2F5ojltQBcP9rdKW4rJFIz6kaGNH+yRXvZJAnX1BHUnz8ciDH4WjDRCFBrIWdjywnl6qa2QVTgIoGDzF0WfTtESenos6leuxHzpFdkiGZfxpoV97qu52behnhVB6Ry9gVBJJmAAbitZWPtOdac9ISdcGWZTfWH8YU/FS+DVvaJMyYz+2MFepiaqWyIhS8XDETWu3CYqtgwGS9ijueb07Vax5mrmmE+2qUrdGDoub0bcH3S+EgChVh1sjAWdayBdLXYtnJbXbhmDvWMG+cBgaVDalB2MUYTIHRsYojyk30xb5PO1dLQraaiSYbgxiJpVX8coAlxBaJkcsKgeP/0nwSwIg6AyjTf9xWC1lkwahzSCNQaWDWxIVy+ZOCdClkGALShu65NTqT6ZMnpnkLQwKIimZR0QSdt1xSyDhPPXt2ohSL28a5nXkCBq+Ux0DmCEiyT1P3cq7V7FrSLa8cXnuv34AqMN5z00I5vhGFi2zj6ElIsjkBsMMZ5QBLCQYZkqErzNzMROod4C+yn3dynz9nuFJCXrZixFrT2cjA5VrpfDoX+SoUozhcgZcbxZb9paRUhrB+Y/Z5j8UoCWjrxUHwMlQvIbvgyRPjENEgiPhaYXdQTf243MyR+LRvsgZ/iOFaroY=
        on:
          repo: renatahodovan/xson
          tags: true
