language: python

install: pip install -U tox
script: tox -v

jobs:
  include:
    - stage: test
      python: 3.4
      env: TOXENV=py
    - python: 3.5
      env: TOXENV=py
    - python: 3.6
      env: TOXENV=py
    - python: 3.7
      env: TOXENV=py
      dist: xenial
    - python: 3.4
      env: TOXENV=lint

    - stage: coverage
      python: 3.4
      env: TOXENV=cov
      before_script: pip install -U coveralls
      after_success: coveralls
